version: "3"

services:

  webapp:
    build:
      context: .
      dockerfile: ./webapp.Dockerfile
    container_name: webapp
    # environment:
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./src/main:/todolist/src/main
      - ./src/test:/todolist/src/test
    ports: 
      - 34637:80
    entrypoint: ["/entrypoint.sh"]

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: todoapp
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/main/resources/model/init_scheme.sql:/docker-entrypoint-initdb.d/init_scheme.sql:ro

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080