spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://mysql-db:3306/todolist?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: todoapp
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 5
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update

  http.encoding:
    charset: UTF-8
    enabled: true

  mvc:
    view.suffix: .jsp
    ignore-default-model-on-redirect: true

server.port: 80